# Generated by Django 2.2.13 on 2022-01-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220127_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='episode_id',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Episode IV'), (5, 'Episode V'), (6, 'Episode VI'), (1, 'Episode I'), (2, 'Episode II'), (3, 'Episode III')], max_length=32),
        ),
    ]
